### ISSUE TITLE
Documentation todo

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi-reactive#41]
- [ ] Why are disposers needed
- [ ] What triggers data loading
- [ ] How does loaded data flow through core
